apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: pooled-secret-store
  namespace: pooling-poc
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-2
      auth:
        jwt:
          serviceAccountRef:
            name: eso-service-account
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-service-account
  namespace: pooling-poc
  annotations:
    eks.amazonaws.com/role-arn: ${ESO_ROLE_ARN}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pooled-db-external-secret
  namespace: pooling-poc
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: pooled-secret-store
    kind: SecretStore
  target:
    name: pooled-db-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: ${POOLED_DB_SECRET_ARN}
        property: password
